### PR TITLE
Make OpSecp256k1Commitment a unary op

### PR DESCRIPTION
**Pull request by petertodd**
See comment re: rational.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you add a note to your doccomment saying that an EC break won't affect the integrity of the commitment operation? (The hash function does the real heavy lifting here, you can use literally any group.)

Other than that, ACK

**Comment by petertodd** [comment]
What would be a better thing for it to say?

Note part of my thinking here is that long term we may want to remove the idea of a binary op entirely.

**Comment by apoelstra** [comment]
I like the existing text, just append "Note that an EC break would not affect the integrity of the commitment, but knowledge of the underlying key may be interesting in its own right." or something.

**Comment by petertodd** [comment]
Done!

I've also timestamped the input to the `secp256k1commitment` op; I'll add that to the timestamp once the timestamp confirms.

**Comment by apoelstra** [comment]
Great, thanks! Let me know if I should rebase this down or something for the real PR.

**Comment by petertodd** [comment]
No need to rebase this - having the commits adds context to the history.

**Pull request merged**
